# Generated by Django 4.2.3 on 2023-07-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=60)),
                ('status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preapproved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_version', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Rejected'), (3, 'Paid')], default=0)),
                ('maximum_payment_date', models.DateTimeField()),
                ('taken_at', models.DateTimeField()),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credicts.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=60)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.SmallIntegerField(choices=[(0, 'Completed'), (1, 'Rejected')], default=0)),
                ('paid_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credicts.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credicts.loans')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credicts.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
