# Generated by Django 4.2.3 on 2023-07-20 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
