# Generated by Django 4.2.3 on 2023-07-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credicts', '0002_alter_customers_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
