# Generated by Django 4.2.3 on 2023-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credicts', '0004_alter_loans_amount_alter_loans_outstanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='maximum_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
