# Generated by Django 4.2.3 on 2023-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credicts', '0005_alter_loans_maximum_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='contract_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Rejected'), (4, 'Paid')], default=1),
        ),
    ]
