# Generated by Django 4.2.3 on 2023-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credicts', '0007_alter_loans_outstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='external_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
